import localFont from "next/font/local";
import "./globals.css";
import Header from "../components/header/header.jsx";

const silkscreen = localFont({
    src: [
        {
            path: "../../public/fonts/Silkscreen-Regular.ttf",
            weight: "400",
            style: "normal",
        },
        {
            path: "../../public/fonts/Silkscreen-Bold.ttf",
            weight: "700",
            style: "normal",
        },
    ],
    variable: "--font-silkscreen",
    display: "swap",
});

export const metadata = {
  title: "Atividade de Revisão",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="pt-br" className={silkscreen.variable}>
      <body className={silkscreen.className}>
        <Header title={"🛒 Loja de Eletrônicos"} subtitle={"Os melhores produtos com os melhores preços"}  />
        {children}
      </body>
    </html>
  );
}
